#+TITLE: ScalaDays 2019
#+AUTHOR:
#+REVEAL_THEME: sky
#+REVEAL_TRANS: default
#+OPTIONS: toc:nil, num:nil

* Report from the Trenches
:PROPERTIES:
:reveal_background: images/olympic-dinner-view.jpg
:reveal_background_trans: slide
:END:

* Events

- Monday: Contributor's Summit

- Tuesday - Thursday: ScalaDays 2019 Talks

- Friday: TypeLevel Summit

** Other Surrounding Events

Various dinners, coding get-togethers and walking tours.

* ScalaDays Talks

... which I Attended

** [[https://scaladays.org/schedule/a-tour-of-scala-3][A Tour of Scala 3]] (Keynote)

Martin Odersky ([[https://www.twitter.com/odersky][@odersky]])

=Summary:=
Some cool new features that makes Scala development easier and simpler for beginners,
as well as many features that will help you when writing functional programs.

** [[https://scaladays.org/schedule/a-story-of-unification-from-apache-spark-to-mlflow][A story of unification: from Apache Spark to MLflow]] (Keynote, possibly sponsored)

Reynold Xin ([[https://www.twitter.com/rxin][@rxin]])

=Summary:= Data pipelines using Scala is cool. DataBricks wants you to use their commercial products.

** [[https://scaladays.org/schedule/techniques-for-teaching-scala][Techniques for Teaching Scala]]

Noel Welsh ([[https://www.twitter.com/noelwelsh][@noelwelsh]])

=Summary:= We should focus on developing our teaching skills. Here are some useful ways to do this in Scala.

** [[https://scaladays.org/schedule/akka-streams-to-the-extreme][Akka Streams to the Extreme]]

Heiko Seeberger ([[https://www.twitter.com/hseeberger][@hseeberger]])

=Summary:= Akka Actors have many anti-patterns. Here is an example where doing distributed computation with Akka Streams can be better.

** [[https://scaladays.org/schedule/massively-parallel-distributed-scala-compilation----and-you][Massively Parallel Distributed Scala Compilation... And You!]]

Stu Hood ([[https://www.twitter.com/stuhood][@stuhood]])

=Summary:= Twitter is doing some amazing things to speed up compilation on a code base with millions of lines of Scala code.

** [[https://scaladays.org/schedule/making-our-future-better][Making Our Future Better]]

Viktor Klang ([[https://www.twitter.com/viktorklang][@viktorklang]])

=Summary:=
In future Future's will still immediately start running when created.
Regardless, there are a few things that can be done to make an eager Future faster and better.
Viktor said they did those things. And notably, they haven't mentioned cats-effect IO, Monix or ZIO.

** [[https://scaladays.org/schedule/the-shapeless-of-type-class-derivation-in-scala-3][The Shape(less) of Type Class Derivation in Scala 3]]

Miles Sabin ([[https://www.twitter.com/milessabin][@milessabin]])

=Summary:=
Miles showed the code that gets generated at compile time when he does a few "simple" but totally incomprehensible things.

The reason why you would want to do these incomprehensible things is incomprehensible.
Maybe it only applies to people writing the Shapeless library.

** [[https://scaladays.org/schedule/concurrent-programming-in-2019-akka-monix-or-zio][Concurrent programming in 2019: Akka, Monix or ZIO?]]

Adam Warski ([[https://www.twitter.com/adamwarski][@adamwarski]])

=Summary:=
An impressive live-coding session where the same problem was solved, first with Akka actors and then with ZIO.

** [[https://scaladays.org/schedule/pure-functional-database-programming-without-jdbc][Pure Functional Database Programming‚ without JDBC]]

Rob Norris ([[https://www.twitter.com/tpolecat][@tpolecat]])

=Summary:=
Rob is the author of the most popular DB library for Scala, [[https://tpolecat.github.io/doobie/][Doobie]] (using JDBC).
JDBC is very old and blocking.
Rob mentioned his new [[https://github.com/tpolecat/skunk][Skunk]] library, and how he used some of the existing pure-functional libraries
(e.g. scodec and FS2) to make a direct TCP connection to PostgreSQL, and do some non-blocking DB queries.

** [[https://scaladays.org/schedule/sustaining-open-source-digital-infrastructure][Sustaining open source digital infrastructure]]

Bogdan Vasilescu

=Summary:=
Bogdan is a professor studying open-source projects.
You should add badges with underlying metrics to your open-source project.

** [[https://scaladays.org/schedule/scalaclean---full-program-static-analysis-at-scale][ScalaClean - full program static analysis at scale]]

Rory Graves ([[https://www.twitter.com/a_dev_musing][@a__dev__musing]])

=Summary:=
If your analysis includes all of the code to be deployed, then [[https://scalacenter.github.io/scalafix/][ScalaFix]] can safely modify the code in interesting ways.
For example, it can change method/class/package visibility to the minimum, or remove unused parameters.

** [[https://scaladays.org/schedule/pick-your-number-type-with-spire][Pick your number type with Spire]]

Denis Rosset

=Summary:=
Spire provides a number of precise number types, but does it perform well enough?
Denis showed a Mandelbrot fractal benchmark using different number types, and on
multiple Scala platforms (JVM, JS and Native).

** [[https://scaladays.org/schedule/compiling-to-preserve-our-privacy][Compiling to preserve our privacy]]

[[https://www.twitter.com/manojah_shanti][Manohar Jonnalagedda]] and [[https://www.twitter.com/jodersky][Jakob Odersky]].

=Summary:=
Suppose you want to get answers from multiple data sources.
But the data in each source can't be shared.

Real world example: certain organisations maintain spy satellites in orbit
around the earth. None of them desire sattelite collisions.
And none of them want to reveal the locations of their sattelites.

** [[https://scaladays.org/schedule/interactive-computing-with-jupyter-and-almond][Interactive Computing with Jupyter and Almond]]

Sören Brunk ([[https://www.twitter.com/soebrunk][@soebrunk]])

=Summary:=

[[https://github.com/almond-sh/almond][Almond]] allows you to write Scala code in your Jupyter notebooks.
The presentation was done entirely within Almond/Jupyter and featured live code
editing from within the presentation.

** [[https://scaladays.org/schedule/all-the-fancy-things-flexible-dependency-management-can-do][All the fancy things flexible dependency management can do]]

Alexandre Archambault ([[https://www.twitter.com/alxarchambault][@alxarchambault]])

=Summary:=
Coursier can do much more than just parallel downloads.
Among other things it can install applications and help bootstrap a clean system
with a Scala dev environment.

* Other ScalaDays Talks

https://scaladays.org/schedule

https://portal.klewel.com/watch/nice_url/scala-days-2019/

* TypeLevel Summit Talks
